[build]
  publish = "."
  functions = "netlify/functions"
  command = "./build.sh"

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/petfinder-proxy/:splat"
  status = 200
  force = true