[build]
  publish = "."
  functions = "netlify/functions"
  command = "npm install && cd netlify/functions && npm install"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/petfinder-proxy/:splat"
  status = 200
  force = true